// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCijbRKz4JkazkzeXvVQ_NTkBHnmltqAxc',
    appId: '1:255204954475:web:f2eae31297d74872c57c2e',
    messagingSenderId: '255204954475',
    projectId: 'users-app-admin',
    authDomain: 'users-app-admin.firebaseapp.com',
    storageBucket: 'users-app-admin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQKxwvOxw6ec5S-EYAakqOF5ytrvGJlk8',
    appId: '1:255204954475:android:6d6556dab4f93419c57c2e',
    messagingSenderId: '255204954475',
    projectId: 'users-app-admin',
    storageBucket: 'users-app-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoXOA4bYgHRDi-Id2NPIbvoWJmwCSZTY4',
    appId: '1:255204954475:ios:2fe228528a1066f1c57c2e',
    messagingSenderId: '255204954475',
    projectId: 'users-app-admin',
    storageBucket: 'users-app-admin.appspot.com',
    iosBundleId: 'com.example.usersApp',
  );
}
